name: show-directory

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run say-hello (from Makefile)
        run: make say-hello

      - name: Show Makefile content (для наглядности)
        run: cat Makefile
